word_dict = {
        'python': 'Popular programming language.',
        'hangman': 'The game you are playing.',
        'challenge': 'A difficult task.',
        'programming': 'Writing computer code.',
        'developer': 'Creates software.',
        'algorithm': 'Step-by-step procedure.',
        'function': 'Code block for a task.',
        'variable': 'Storage for data.',
        'syntax': 'Rules for coding.',
        'loop': 'Repeats code.',
        'condition': 'True or false check.',
        'string': 'Sequence of characters.',
        'integer': 'Whole number.',
        'float': 'Decimal number.',
        'boolean': 'True or false value.',
        'list': 'Ordered collection.',
        'tuple': 'Immutable collection.',
        'dictionary': 'Key-value pairs.',
        'set': 'Unique items collection.',
        'module': 'Python file.',
        'package': 'Collection of modules.',
        'library': 'Precompiled routines.',
        'framework': 'Platform for apps.',
        'software': 'Programs for computers.',
        'hardware': 'Physical computer parts.',
        'network': 'Connected computers.',
        'database': 'Structured data storage.',
        'server': 'Provides resources.',
        'client': 'Requests resources.',
        'protocol': 'Rules for data exchange.',
        'security': 'Protection from threats.',
        'encryption': 'Securing data.',
        'decryption': 'Decoding data.',
        'authentication': 'Verifying identity.',
        'authorization': 'Permission to access.',
        'firewall': 'Network security system.',
        'malware': 'Harmful software.',
        'virus': 'Malicious code.',
        'trojan': 'Disguised malware.',
        'worm': 'Self-replicating malware.',
        'spyware': 'Secretly monitors activity.',
        'adware': 'Displays ads.',
        'ransomware': 'Holds data for ransom.',
        'phishing': 'Fraudulent information request.',
        'hacking': 'Unauthorized access.',
        'bug': 'Programming error.',
        'debug': 'Fixing errors.',
        'testing': 'Evaluating software.',
        'deployment': 'Releasing software.',
        'virtualization': 'Creating virtual resources.',
        'container': 'Package of software.',
        'docker': 'Container platform.',
        'kubernetes': 'Manages containers.',
        'cloud': 'Internet computing.',
        'aws': 'Amazon cloud service.',
        'azure': 'Microsoft cloud service.',
        'google': 'Search engine giant.',
        'microservices': 'Small, autonomous services.',
        'monolithic': 'Tightly coupled system.',
        'scalability': 'Handles growth.',
        'performance': 'Efficiency of system.',
        'optimization': 'Improving efficiency.',
        'cache': 'Fast data storage.',
        'memory': 'Quick access storage.',
        'disk': 'Storage device.',
        'cpu': 'Computer processor.',
        'bandwidth': 'Data transfer rate.',
        'latency': 'Delay in data transfer.',
        'throughput': 'Data processing rate.',
        'api': 'Application interface.',
        'rest': 'Web service design.',
        'graphql': 'Query language for APIs.',
        'soap': 'Protocol for web services.',
        'json': 'Data format.',
        'xml': 'Markup language.',
        'html': 'Web page language.',
        'css': 'Styles web pages.',
        'javascript': 'Web programming language.',
        'typescript': 'JavaScript superset.',
        'react': 'JavaScript library.',
        'angular': 'Web application framework.',
        'vue': 'JavaScript framework.',
        'node': 'JavaScript runtime.',
        'express': 'Node.js framework.',
        'django': 'Python web framework.',
        'flask': 'Micro web framework.',
        'spring': 'Java framework.',
        'laravel': 'PHP framework.',
        'ruby': 'Programming language.',
        'rails': 'Ruby framework.',
        'php': 'Web development language.',
        'java': 'Object-oriented language.',
        'kotlin': 'Java alternative.',
        'swift': 'Apple programming language.',
        'objective': 'Previous Apple language.',
        'csharp': 'Microsoft language.',
        'golang': 'Google language.',
        'rust': 'Systems programming language.',
        'scala': 'JVM language.',
        'elixir': 'Erlang-based language.',
        'haskell': 'Functional programming language.',
        'clojure': 'Lisp on JVM.',
        'perl': 'Scripting language.',
        'binary': 'Base-2 numbering system.',
        'hexadecimal': 'Base-16 numbering system.',
        'algorithmic': 'Relating to algorithms.',
        'iteration': 'Repetition in processes.',
        'recursion': 'Function calling itself.',
        'compilation': 'Converting code to executable.',
        'interpreter': 'Executes code line-by-line.',
        'compiler': 'Transforms code into machine code.',
        'byte': '8 bits of data.',
        'bit': 'Smallest data unit.',
        'unicode': 'Universal text encoding.',
        'ascii': 'Character encoding standard.',
        'bandwidth': 'Maximum data capacity.',
        'thread': 'Smallest unit of execution.',
        'process': 'Running instance of a program.',
        'hypervisor': 'Manages virtual machines.',
        'virtual machine': 'Simulated computer system.',
        'load balancer': 'Distributes network traffic.',
        'proxy': 'Intermediary server.',
        'session': 'Interaction between client and server.',
        'cookie': 'Stores user data.',
        'cache miss': 'Data not found in cache.',
        'cache hit': 'Data retrieved from cache.',
        'domain': 'Address of a website.',
        'dns': 'Translates domain names to IP.',
        'ip address': 'Unique network identifier.',
        'tcp': 'Reliable transmission protocol.',
        'udp': 'Unreliable but fast protocol.',
        'ping': 'Test connectivity latency.',
        'traceroute': 'Shows packet travel path.',
    }